sudo: false

language: java
jdk:
  - oraclejdk8
env:
  global:
    - secure: "j+T2uTFSus9e2GrTYgZsnLOwOAvrMQ6PSQjQJLebRtrqZN/wzR4BL3vHQ98CaJJC42OmAiYPsE/rSKso1hNiooe8sj+XDTipSuutOL+/4MfDhkpAQQ8+XTo86GOjHClwPpCTItwovkTesYzLuYlQ37ust92VlADlf9aP8R/ftabtxbcD+nT21MPuo8SLJQfvNSgHQ/shy8wEMjV+ljOEti8lKvJAHZxfseym5Q+0e+tHtkSqssQ2F9iGP9OfLJ2x8TMpLyPIlqacBrciVAD8j1SCf5C7vXCKsb6GXrkAK/m50Bw0pLFgeIJo5aAJtcG+4QXuYyc9OHOWXNZTn0aQnBI7CwJBRSeGlEcD8XRJZpH0B/kjB7kVYiZp8PtUTzXJjsJpbS5V3sHd08Kwf2dyPP0TryfauUGc0bezopLzVS8oP/262erSDrZVLBPM5vySYoQi5NEcAmiX8NJUTjgjHwCCbu+OLvNBJJigl3FFFhEZpzoew/OBxW/CILspt7gl+KMJFJWf21g8CPF0hm/KbiQGICTTU8SMTIW1mtnqsEs5u9fSppEMSBScKAZt4JbuZXvk1A12UEBesAE5JjYfEBUIgavMVxjZ0a4c1tPnzqrJCsnwUNqEZ2114B0UJkZj6UCXrTHLysC5fJw/VtKDv7ua5aiJgdY6hAt1yBG/CaA="
cache:
  directories:
    - $HOME/.m2
  
script: 
  - "mvn cobertura:cobertura"
  - "mvn javadoc:javadoc"

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - bash Deploy_JavaDoc.sh

notification:
  email:
    on_success: never
    on_failure: always
